services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M
        reservations:
          memory: 16M

networks:
  app-network:
    driver: bridge
